emails:
  - "jordan.mariani@gmail.com"
  - "melia94@hotmail.com"

logger:
  type: "wazuh"
  file_path: "logs.json"

checker:
  type: "leakcheck"

notifier:
  type: "thehive"
  api_url: "http://localhost:9000"
  api_key: "Oomcp1tNtGZLqBFBOAslAoI4ZkHkbrKy"
  organisation: "family"