name: Go Build, Test, Deploy, and Shell Script Security Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Run gosec
      uses: securego/gosec@master
      with:
        args: ./...

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3

    - name: Install ShellCheck
      run: sudo apt-get install -y shellcheck

    - name: Run ShellCheck
      run: shellcheck deploy.sh
